# Generated by Django 5.1.2 on 2024-10-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phno', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('stid', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('paswrd', models.CharField(blank=True, max_length=8, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('admno', models.IntegerField(blank=True, null=True)),
                ('jdate', models.DateField(blank=True, null=True)),
                ('dpt', models.CharField(blank=True, max_length=25, null=True)),
                ('bloodgrp', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=15)),
                ('parentno', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
