# Generated by Django 4.2.11 on 2024-11-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomGenie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregister',
            old_name='address',
            new_name='adrs',
        ),
    ]
