# Generated by Django 5.1.4 on 2024-12-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomGenie', '0003_parentregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
