# Generated by Django 5.1.3 on 2024-12-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomGenie', '0004_alter_studentregister_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentregister',
            name='sname',
        ),
        migrations.AddField(
            model_name='parentregister',
            name='svname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomGenie.studentregister'),
        ),
    ]
