# Generated by Django 5.0.6 on 2024-12-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomGenie', '0005_remove_parentregister_sname_parentregister_svname'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('stname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RoomGenie.studentregister')),
            ],
        ),
    ]
