# Generated by Django 5.0.6 on 2024-12-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomGenie', '0006_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='stcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
